### ISSUE TITLE
Dataplattform Covid-19 spesial: febermåling ved bruk av kontoret

### ISSUE THREAD

**Issue by jensmark** [knowit/Dataplattform-issues#235]
Kanskje Dataplatform kunne kjøpt https://www.clasohlson.com/no/Withings-Thermo,-febertermometer/p/44-4279?gclid=EAIaIQobChMIst2Fhv7E6wIVw9myCh1ReQDWEAYYAiABEgKMv_D_BwE og satt ved inngangene, og henta opp data via https://developer.withings.com/oauth2/? 

Er jo kjekt i disse dager. Eventuellt kobla opp og henta data fra:https://www.clasohlson.com/no/Withings-Core,-blodtrykksm&aring;ler/p/Pr444278000. Vi som har så stillesittende yrke, trenger en blodtrykktest i ny og ne, også får vi data på helsen til firmaet. 

Selvfølgelig må det være anonymt å dele dataene.

**Comment by torjohannessen** [comment]
Utgått på dato
