### ISSUE TITLE
Kompetansekartlegging - Ferdigstille "Rediger superadminer"

### ISSUE THREAD

**Issue by krisstam** [knowit/Dataplattform-issues#651]
Legg til funksjonalitet slik at en Superadmin kan gi/fjerne superadmin roller v.h.a et UI.

Forslag til endring:
Bruk gjerne designet som er der, og oppdater det slik at det viser brukere fra alle organisasjoner, samt at man kan se hvilken organisasjon en bruker tilhører.

**Comment by torjohannessen** [comment]
Allerde overført til KK.app
